biolib_version: 2
modules:
    main:
        image: 'local-docker://nsp-docker:latest'
        command: python predict.py
        working_directory: /home/biolib/
        input_files:
            - COPY / /home/biolib/
        output_files:
            - COPY /home/biolib/ /
        source_files:
            - COPY / /home/biolib/
arguments:
    -
        default_value: ''
        description: Insert fasta sequence(s)
        key: '--fasta-file'
        key_value_separator: ' '
        required: true
        type: file